@host = http://localhost:3000
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTY2MzU3MjZ9.OByaZjg58fDUziKbsMls82IOXIaYM33tdD81NevDqtQ

### Students Index
GET {{host}}/students.json

### Students Create
POST {{host}}/students.json
Content-Type: application/json

{
  "first_name": "Test",
  "last_name": "test",
  "email": "test@gmail.com",
  "phone_number": "8005555555",
  "short_bio": "short bio",
  "LinkedIn_URL": "LinkedIn_URL",
  "twitter_handle": "@twitter_handle",
  "personal_blog": "personal_blog",
  "online_resume_url": "online_resume_url",
  "github_url": "github_url",
  "photo": "photo"
}

### Users Create (signup)
POST {{host}}/users.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{host}}/sessions.json
Content-Type: application/json

{
 "email": "test@test.com",
 "password": "password"
}


### Students create
POST {{host}}/students.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
"first_name": "Test name",
"last_name": "Test lastname",
"email": "Test@test.com",
"phone_number": "73737467",
"short_bio": "something" ,
"LinkedIn_URL": "test.LinkedIn_URL" ,
"twitter_handle": "@test" ,
"personal_blog": "something else" ,
"online_resume_url": " www.test.test" ,
"github_url": "test.github.com",
"photo": "test.url" 
}

### Students Show 
GET {{host}}/students/2.json


### Students Update
PATCH {{host}}/students/4.json
Content-Type: application/json

{
  "first_name": "test2",
  "last_name": "test3",
  "email": "newtest@gmail.com"
}

### Students Destroy
DELETE {{host}}/students/5.json

